[SERVICE]
    Flush                 5
    Log_Level             info
    Parsers_File          parsers.conf
    storage.path          /var/lib/fluent-bit/storage
    storage.sync          normal
    storage.checksum      on
    storage.backlog.mem_limit 5M

[INPUT]
    Name                  tail
    Path                  /root/.pm2/logs/*.log
    Tag                   frolens.pm2
    DB                    /var/lib/fluent-bit/frolens-pm2.db
    Read_from_Head        Off
    Refresh_Interval      5
    Rotate_Wait           30
    Skip_Long_Lines       On

[INPUT]
    Name                  tail
    Path                  /var/log/nginx/access.log
    Tag                   frolens.nginx.access
    DB                    /var/lib/fluent-bit/frolens-nginx-access.db
    Read_from_Head        Off
    Refresh_Interval      5
    Rotate_Wait           30
    Skip_Long_Lines       On

[INPUT]
    Name                  tail
    Path                  /var/log/nginx/error.log
    Tag                   frolens.nginx.error
    DB                    /var/lib/fluent-bit/frolens-nginx-error.db
    Read_from_Head        Off
    Refresh_Interval      5
    Rotate_Wait           30
    Skip_Long_Lines       On

[OUTPUT]
    Name                  http
    Match                 frolens.*
    Host                  ${IONOS_LOG_HOST}
    Port                  443
    URI                   /${IONOS_LOG_TAG}
    Format                json
    Header                APIKEY ${IONOS_LOG_APIKEY}
    tls                   On
    Retry_Limit           False